import fs from 'fs-extra';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Run LLM analysis on a packed repomix file
 * @param {string} filePath - Absolute path to the packed repomix file
 * @param {string} repoName - Name of the repository for context
 * @returns {Promise<string>} - Markdown report
 */
export async function analyzeRepository(filePath, repoName) {
  const apiKeysRaw = process.env.GEMINI_API_KEY;
  if (!apiKeysRaw) {
    throw new Error('Gemini API Key is not configured. Please set GEMINI_API_KEY in the .env file.');
  }
  const apiKeys = apiKeysRaw.split(',').map(k => k.trim()).filter(Boolean);
  if (apiKeys.length === 0) {
    throw new Error('Gemini API Key is not configured. Please set GEMINI_API_KEY in the .env file.');
  }

  // Check if file exists
  if (!await fs.pathExists(filePath)) {
    throw new Error(`Repomix output file not found at ${filePath}`);
  }

  // Read file contents
  // Let's cap the read size to prevent loading massive files entirely into memory (e.g., limit to ~6MB or ~1.5 million tokens)
  const stats = await fs.stat(filePath);
  const maxBytes = 6 * 1024 * 1024; // 6MB limit for safety
  
  let fileContent = '';
  if (stats.size > maxBytes) {
    console.log(`File size is ${stats.size} bytes. Truncating to first ${maxBytes} bytes for API request.`);
    const fd = await fs.open(filePath, 'r');
    const buffer = Buffer.alloc(maxBytes);
    await fs.read(fd, buffer, 0, maxBytes, 0);
    await fs.close(fd);
    fileContent = buffer.toString('utf8') + '\n\n...[Truncated due to token size limits]...';
  } else {
    fileContent = await fs.readFile(filePath, 'utf8');
  }

  // Construct Prompt
  const prompt = `You are an expert software architect and security auditor.
Analyze the following codebase context (which was generated by Repomix) and provide a comprehensive Repository Analysis Report.

Your report must be structured as follows:

# Repository Analysis Report: ${repoName}

## 1. Project Overview & Architecture
- **Primary Technologies & Languages**: List the main programming languages, frameworks, and libraries used.
- **Architecture Style**: Describe the architectural pattern (e.g., Monolith, MVC, Clean Architecture, Serverless) and codebase layout.
- **Core Components**: Identify the main directories and their responsibilities.

## 2. Key Modules & Entry Points
- **Entry Points**: Where does the application start (main scripts, server entry points, etc.)?
- **Key Modules**: Describe 3-5 of the most important modules/files and what they do.

## 3. Code Quality & Best Practices
- **Strengths**: What is done well in this codebase (e.g., clean structure, comprehensive testing, types, documentation)?
- **Areas for Improvement**: Identify concrete opportunities to refactor, modularize, or clean up code.

## 4. Security & Performance Audit
- **Security Observations**: Any potential security vulnerabilities, unsafe functions, missing validation, or exposed configurations.
- **Performance Observations**: Any potential bottlenecks, memory leaks, or slow operations.

## 5. Summary & Next Steps
- A 3-bullet-point summary of what to work on next for this project.

Here is the codebase context:
--- START OF CODEBASE CONTEXT ---
${fileContent}
--- END OF CODEBASE CONTEXT ---`;

  console.log(`Sending repository analysis request to Gemini for "${repoName}" (${stats.size} bytes)...`);

  // Call Gemini API using standard fetch
  const model = 'gemini-2.5-flash';
  let lastError = null;
  let response = null;

  for (const key of apiKeys) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;
    console.log(`Attempting Gemini API request with key starting with: ${key.slice(0, 8)}...`);
    try {
      response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.2,
            topP: 0.95,
            topK: 40,
            maxOutputTokens: 8192,
            responseMimeType: 'text/plain'
          }
        })
      });

      if (response.ok) {
        break;
      } else {
        const errorText = await response.text();
        let parsedError;
        try {
          parsedError = JSON.parse(errorText);
        } catch {
          parsedError = errorText;
        }
        const errMsg = parsedError?.error?.message || errorText;
        console.warn(`Gemini API key starting with ${key.slice(0, 8)} failed: status ${response.status} - ${errMsg}`);
        lastError = new Error(`Gemini API request failed with status ${response.status}: ${errMsg}`);
      }
    } catch (err) {
      console.warn(`Network error with Gemini API key starting with ${key.slice(0, 8)}: ${err.message}`);
      lastError = err;
    }
  }

  if (!response || !response.ok) {
    throw lastError || new Error('All configured Gemini API keys failed.');
  }

  const result = await response.json();
  const reportText = result?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!reportText) {
    throw new Error('Received empty response from Gemini API.');
  }

  return reportText;
}
